// `chuxue`.`sys_dbms_tabs_table_info`   
export interface SysDbmsTabsTableInfo{
  createTime?: Date,
  createUser?: string,
  deleteFlag?: number,
  discription?: string,
  dissql?: number,
  jdbcUuid?: string,
  sort?: number,
  tabsDesc?: string,
  tabsName?: string,
  tabsRows?: number,
  tabsSpace?: string,
  typeCode?: string,
  updateTime?: Date,
  updateUser?: string,
  uuid?: string,
}

export interface SysDbmsTabsCols{
  uuid: string,
  updateTime?: Date,
  createTime?: Date,
  sort?: string,
  colsDefault?: string,
  userIcon?: string,
  updateUser?: string,
  colsWidth?: number,
  discription?: string,
  indexCode?: string,
  tabsUuid?: string,
  colsValign?: string,
  colsLength?: string,
  nullable?: string,
  colsSwitchable: string,
  colsName: string,
  deleteFlag: number,
  dataPrecision: string,
  colsDesc?: string,
  dataScale: string,
  colsType: string,
  createUser?: string,
  dataType?: string,
  colsAlign: string,
}
